### PR TITLE
Ft push notifications

### PR DESCRIPTION
**Pull request by johnseremba**
## PR Status
**READY**

## Story ID
* [Push Notifications Page](https://trello.com/c/VKpEogz4/47-push-notifications-page)

## Description
* Functionality for sending push notifications to either all users of the App, or by location.
* Added push notification preview functionality. It gives the user a look and feel of how the push notification shall be displayed on the client device.
* Added an audience object that takes in a `field` found in the `Installation` Parse model and a `value` that you would like to compare against.

## New Packages Added
* None

## Todos
- [x] Tested and working locally
- [x] Tested and working on development environment
- [ ] Added more Unit tests (if appropriate)
- [ ] Reviewed and approved by a senior dev

## Steps to Test or Reproduce

```sh
git pull --prune
git checkout <ft-push-notifications>
```

## Impacted Areas in Application
This PR will affect:
* push-notifications component
* stories component
* services > notifications

# Known Issues
* Timezones currently are hard-coded in an array because Parse doesn't provide a mechanism for getting distinct query results. So, It made no sense to me to query hundreds of records, yet the unique timezones may be only 2 or 3.

* The Android App currently only recognizes push notifications for Assignments. We may have to configure the app to accept general notifications too. That is why the notification may appear blank on the phone, yet the notification has been created in the Parse Backend.

### CODE REVIEW

**Comment by phillipahereza** [comment]
@SerryJohns do the push notifications work? Can I make push notifications from the dashboard?

**Comment by johnseremba** [comment]
@phillipahereza Yes, the work. Notifications are sent. You can try it.
There is just a configuration issue at the App side.

**Comment by phillipahereza** [comment]
@SerryJohns there's no feedback after send a push notification. Could you incorporate that

**Comment by phillipahereza** [comment]
@SerryJohns align this properly 
screen shot 2017-11-03 at 9 01 14 am

**Comment by johnseremba** [comment]
@phillipahereza Its done. I have fixed the alignment.

**Pull request merged**
