### PR TITLE
Ft add analytics

### PR DESCRIPTION
**Pull request by EdwinKato**
## PR Status
**READY**

## Story ID
https://trello.com/c/926F9Xvy/49-analytics
https://trello.com/c/QSXCvh44/48-overview

## Description
* Integrate flurry data into the dashboard
* Integrate ngx-charts
* Display graphical representation of the data
* Write algorithms to pass data from flurry to the graphs in an ordered way
* Work on overview page
* Integrate events analytics

## New Packages Added
ngx-charts

## Related PRs
None

## Todos
- [x] Add loading indicator on graphs loading
- [x] Format event names and display in more legible format
- [x] Add more colours to the line chart
- [x] Add pagination
- [x] Add search function
- [x] Add more data on overview page

## Impacted Areas in Application
* Overview
* Events summary

## Known Issues
* None

### CODE REVIEW

**Comment by phillipahereza** [comment]
@EdwinKato events summary, legend only has 2 colors. Kinda confusing if you want to use the line graph to see the custom events.
screen shot 2017-11-02 at 10 00 51 pm

And for the custom events, could you pretty display them e.g. PASSWORD_SIGN_UP to number of sign ups using password

The graphs take a while to load, some feedback to the user would be nice. Maybe a loading animation. Blank pages are unnerving

**Comment by phillipahereza** [comment]
@EdwinKato in future we might have very many custom events so a paginated searchable list would be nice

**Comment by phillipahereza** [comment]
@EdwinKato I think you can add some more data to the overview page

**Comment by EdwinKato** [comment]
@phillipahereza Thanx for the feedback. I will surely incorporate it in. Concerning providing the users with feedback while the graphs are loading, functionality for that is already there but the styles are in John's PR. These will reflect later on when everything is merged.

**Comment by EdwinKato** [comment]
@phillipahereza Could you also shade more light on the kind of information that you would like to be added on the overview page?

**Pull request merged**
